### ISSUE TITLE
Labels in figure labels in intro_to_pyemu possibly wrong

### ISSUE THREAD

**Issue by Hugovdberg** [gmdsi/GMDSI_notebooks#148]
I believe the x-labels of these two plots are switched up, the first showing the original values, and the second showing the $log_{10}$ of the values, revealing the log-normal nature of the realisations. 

https://github.com/gmdsi/GMDSI_notebooks/blob/47aff10a5cd172bd7c16002d71134629faabcf55/tutorials/part0_intro_to_pyemu/intro_to_pyemu.ipynb#L1566
https://github.com/gmdsi/GMDSI_notebooks/blob/47aff10a5cd172bd7c16002d71134629faabcf55/tutorials/part0_intro_to_pyemu/intro_to_pyemu.ipynb#L1600

**Comment by rhugman** [comment]
Thanks for this. Pull requests are welcome!
