### ISSUE TITLE
Notebooks giving AssertionError

### ISSUE THREAD

**Issue by CooperGarth** [gmdsi/GMDSI_notebooks#153]
When the note book runs line 14 the `assert "dependencies" in flopy.__file__` I get the error `AssertionError`: .

Tried to install latest version of anacondas, flopy and pyemu.

**Comment by mnfienen** [comment]
Hi @CooperGarth  - it is important to install an environment using the instructions on the [README](https://github.com/gmdsi/GMDSI_notebooks?tab=readme-ov-file#installation-instructions) file and the exact envrionemnt.yml file we provided. This does not install flopy and pyemu, but rather uses the versions of those codes that are tracked within this reporitory. We do this to make sure that all the notebooks work with the specific python and flopy/pyemu.

Please give that a try.

**Comment by CooperGarth** [comment]
Thanks @mnfienen I tried the README file instructions - they didn't work (could be lack for python knowledge). I deleted lines 14 and 15 and the notebooks worked.
