### ISSUE TITLE
MemoryError: Unable to allocate 28.9 GiB for an array with shape (62227, 62227) and data type float64

### ISSUE THREAD

**Issue by hjia1005** [gmdsi/GMDSI_notebooks#44]
Hi,

I am running the freyberg_obs_and_weights.ipynb and run into this error message. My pc is not able to deal with that size of matrix. Any other way to get it run?

![image](https://user-images.githubusercontent.com/33449394/174717942-cef7ef69-c73d-4cdc-8b8c-6ccfcef39738.png)

**Comment by jtwhite79** [comment]
It seems like there are far too many nonzero weighted observations at that point in tbe workflow.  Did you run the pstfrom notebook first?  If so, can you try restarting the kernel and running all cells from top to bottom?

**Comment by hjia1005** [comment]
Yes, I had something wrong in the pstfrom notebook and didn't try to fix it before I ran the obs_and_weight notebook. All good now. Thank you very much for your reply!
