### ISSUE TITLE
Starting to review

### ISSUE THREAD

**Issue by mnfienen** [gmdsi/GMDSI_notebooks#52]
Hey @rhugman  and @jtwhite79:

I'm finally digging into these notebooks (nice work!). I'm working in a branch called `mike_review`. Looks like I will need more rights to push the branch.

If it's cool, I can keep track of comments in an issue to make it easier to see what I comment on.

Also, I have a path to USGS review and should be pretty straightforward.

Let me know if this sounds good.

**Comment by rhugman** [comment]
Thanks @mnfienen, that's great!

Re- issues as comments: works for me. Let me know once you are at a point that I can start working on addressing them.

You have Admin rights to the organization/repo and should be able to push the branch:

![image](https://user-images.githubusercontent.com/60137311/186285976-282481d9-987b-4da3-a7f4-289d156cbc1f.png)

**Comment by mnfienen** [comment]
cool - thanks. I'll keep rolling with the issues approach then. Not sure why I can't push - I'll sort that out
