### ISSUE TITLE
freyberg_monte_carlo

### ISSUE THREAD

**Issue by mnfienen** [gmdsi/GMDSI_notebooks#58]
This is blowing up in the second part when sampling using FOSM for a constrained MC.

**Comment by mnfienen** [comment]
looks like @jtwhite79  found an issue with SWEEP and the regularization phi calculations that he will fix that should sort this out

**Comment by JackElsey** [comment]
I was able to run the [notebook](https://github.com/gmdsi/GMDSI_notebooks/blob/main/tutorials/part1_12_monte_carlo/freyberg_monte_carlo.ipynb) you're presumably referring to without any issues.
