### ISSUE TITLE
OPT

### ISSUE THREAD

**Issue by mnfienen** [gmdsi/GMDSI_notebooks#62]
Specifying `font: 'normal'` is throwing a warning - do we need that?

Should we add multiple constraints in the first NB such that total GW pumping requirement is met in each SP?

**Comment by jtwhite79** [comment]
I added that font stuff to deal with the mircofont that mpl was giving me...

I think we have GW pumping constraints for the last 12 stress periods:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/1770912/187512348-2baf3fa5-a9c4-4838-a2b1-e341f904dda1.png">

**Comment by mnfienen** [comment]
I'll try with specifying font size only - it's the "normal" part that throws an error. 

You are right about the constraints - I misunderstood thinking it was the sum of those (you showed SFR above but same goes for WEL). So all good methinks

**Comment by mnfienen** [comment]
JK all gut
