### ISSUE TITLE
intro to freyberg notebook snaggles

### ISSUE THREAD

**Issue by kmarkovich-intera** [gmdsi/GMDSI_notebooks#65]
Hello, I am working through the develop branch notebooks and ran into 2 issues with the intro to freyberg notebook. First, the sim.run_simulation() command throws an "Exception: The program mf6.exe does not exist or is not executable." I confirmed that mf6.exe is in the sim_ws and runs fine outside of the notebook, so I am not sure why it's not finding it. FWIW I am running these on a PC and with the gmdsi conda env. 

Second, the obs v sim plot for GAGE-1 throws an error due to a key mismatch. In the truth csv it's called "GAGE-1" but in the obs file and csv output it is "GAGE_1." Renaming the former to be GAGE_1 fixes the problem.

**Comment by mnfienen** [comment]
Hi @kmarkovich-intera  - thanks for finding this! First question is are you running in the `main` branch or `develop`? This is all working for me in `develop`.

On the exe, can you confirm whether `mf6.exe` got properly copied over into the run directory (e.g. `freyberg_mf6`?

**Comment by kmarkovich-intera** [comment]
I'm on the develop branch and yes mf6.exe was properly copied. I can run the model with it directly, just not via sim.run_simulation(). Super weird!

**Comment by mnfienen** [comment]
that is weird! Have you pulled develop? We merged in a bunch of stuff yesterday.

Also, strangely, I'm seeing `gage-1` in the `sfr.obs` file and `GAGE-1` in the `sfr.csv` file, so something is mismatched....

**Comment by mnfienen** [comment]
Maybe to confirm, this is what I see in `git log` for `develop`:
```commit 631f04934312eec935cc240eecbfa4eff6892f7b (HEAD -> develop, upstream/develop)
Merge: 2bd8d76 44c90ae
Author: mnfienen <mnfienen@usgs.gov>
Date:   Wed Sep 7 12:00:45 2022 -0500

    Merge pull request #64 from mnfienen/mike_review_2
    
    Mike review 2

commit 44c90aedf3bade44014440c13bcd42fb9fa9fdb9
Merge: 926e011 9fa3fd3
Author: mnfienen <mnfienen@usgs.gov>
Date:   Wed Sep 7 09:40:37 2022 -0500

    Merge pull request #2 from jtwhite79/mike_review_2
    
    Mike review 2

**Comment by kmarkovich-intera** [comment]
I forked it yesterday, so that might be the issue...

**Comment by mnfienen** [comment]
sounds likely :)

**Comment by kmarkovich-intera** [comment]
Merge: 2bd8d76 44c90ae
Author: mnfienen <mnfienen@usgs.gov>
Date:   Wed Sep 7 12:00:45 2022 -0500

    Merge pull request #64 from mnfienen/mike_review_2

    Mike review 2

commit 44c90aedf3bade44014440c13bcd42fb9fa9fdb9
Merge: 926e011 9fa3fd3
Author: mnfienen <mnfienen@usgs.gov>
Date:   Wed Sep 7 09:40:37 2022 -0500

    Merge pull request #2 from jtwhite79/mike_review_2

    Mike review 2

**Comment by kmarkovich-intera** [comment]
Seems up to date with yours? Now I'm really confused

**Comment by mnfienen** [comment]
me too!!! 

I hate to suggest, but maybe clone a gain to be sure? 
<img width="356" alt="image" src="https://user-images.githubusercontent.com/1110827/189213283-7f37218a-33dc-4b5e-9377-85b662d40346.png">

**Comment by kmarkovich-intera** [comment]
Will do!

**Comment by mnfienen** [comment]
sorry for the trouble!

**Comment by kmarkovich-intera** [comment]
Honestly, I blame this new Dell that I was forced to receive. Deleted repo, fresh clone from gmdsi repo (not my fork), switched to develop branch, and boom, same issue!

**Comment by kmarkovich-intera** [comment]
Just gave it the full exe path and it worked... maybe it was expecting to see it one level up from sim_ws? Do you have mf6.exe in your root path? I don't on this machine
![image](https://user-images.githubusercontent.com/84793890/189214631-ce4a5db8-1c83-4853-a0af-26a8e56bce2e.png)

**Comment by mnfienen** [comment]
Oh man - yeah, that makes sense. I do have `mf6` in my path. Crumbs. Thanks for the catch! I'll commit up a change.

I'm still confused about the `GAGE_1` vs. `GAGE-1` issue. I don't see `GAGE_1` anywhere.....

**Comment by kmarkovich-intera** [comment]
[obs_data.csv](https://github.com/gmdsi/GMDSI_notebooks/files/9530294/obs_data.csv)
This is the obs_data.csv in models/daily_freyberg_mf6_truth/ from my fresh pull.

**Comment by mnfienen** [comment]
right. cool - it's `GAGE-1` in there so should work no?

**Comment by kmarkovich-intera** [comment]
Oh yeah! seems like re-pulling fixed that one. Nice.

**Comment by mnfienen** [comment]
sweet! so you are good then?

**Comment by kmarkovich-intera** [comment]
Yes, thanks! Onto the next one...

**Comment by mnfienen** [comment]
awesome! closing then
