### ISSUE TITLE
part0_01_freyberg_trial_and_error can't find flopy

### ISSUE THREAD

**Issue by kmarkovich-intera** [gmdsi/GMDSI_notebooks#66]
First code cell throws a module not found error for flopy. Adding `sys.path.append(os.path.join("..", "..", "dependencies"))` right after `import sys` fixes it. This is using the gmdsi conda env provided with the tutorial.

**Comment by mnfienen** [comment]
Thanks, @kmarkovich-intera - you are correct. I fixed in my branch but having some trouble incorporating in to the main codebase. I will try again tomorrow

**Comment by mnfienen** [comment]
I think it's sorted now. Cheers!
