### ISSUE TITLE
How to run part 1 in batch?

### ISSUE THREAD

**Issue by GMartinez-intera** [gmdsi/GMDSI_notebooks#68]
Hello,

I am starting on the hypothesis testing notebook idea, any recommendations on how to run part 1 in the develop branch?  After activating gmdsitut, I am trying to run tutorials>python run_part1_notebooks.py. Is this the right script? I can see it has options to generate pdf and html files of the tutorials.

Thanks!

**Comment by GMartinez-intera** [comment]
(gmdsitut) C:\INTERA\R&D\GMDSI\GMDSI_notebooks\tutorials>python run_part1_notebooks.py
[NbConvertApp] Converting notebook intro_to_regression.ipynb to notebook
[NbConvertApp] Writing 560942 bytes to intro_to_regression.ipynb
[NbConvertApp] Converting notebook intro_to_regression.ipynb to html
[NbConvertApp] Writing 1156010 bytes to intro_to_regression.html
preped htmlfile:  C:\INTERA\R&D\GMDSI\GMDSI_notebooks\docs\intro_to_regression.html
Traceback (most recent call last):
  File "C:\INTERA\R&D\GMDSI\GMDSI_notebooks\tutorials\run_part1_notebooks.py", line 35, in <module>
    run_nb(nb_file, nb_dir)
  File "C:\INTERA\R&D\GMDSI\GMDSI_notebooks\tutorials\run_part1_notebooks.py", line 14, in run_nb
    os.chdir(nb_dir)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'freyberg_intro_to_model'

**Comment by GMartinez-intera** [comment]
I am guessing the script needs to be updating given the new file nomenclature.

**Comment by rhugman** [comment]
Thanks for catching this. Should be fixed with #71.
