### ISSUE TITLE
getting OS agnostic run calls in intro_freyberg_model (error in Windows)

### ISSUE THREAD

**Issue by GMartinez-intera** [gmdsi/GMDSI_notebooks#69]
Hello,

The third cell in notebooks/intro_to_freyberg_model/intro_freyberg_model.ipynb is giving me an error. Manual DOS testing shows mf6.exe is there. Exported py script gives the same error.  Please let me know if you need more details

Cell In [20], line 11 (I added some diagnostic lines to check)
      8 print(os.getcwd())
     10 # run the model
---> 11 sim.run_simulation()

dependencies\flopy\mbase.py:1701, in run_model(exe_name, namefile, model_ws, silent, pause, report, normal_msg, use_async, cargs)
   1699         exe = which(exe_name[:-4])
   1700 if exe is None:
-> 1701     raise Exception(
   1702         f"The program {exe_name} does not exist or is not executable."
   1703     )
   1704 else:
   1705     if not silent:

Exception: The program mf6.exe does not exist or is not executable.

**Comment by GMartinez-intera** [comment]
This fix might help on evaluating the problem. Thank you!

https://github.com/gmdsi/GMDSI_notebooks/issues/65#issuecomment-1241172557

**Comment by rhugman** [comment]
Just to confirm, has this issue been resolved? Can we close it?
